# Generated by Django 2.2.5 on 2021-10-24 09:20

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ccy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='CcyPair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_ccy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='base_ccy', to='swpm.Ccy')),
                ('quote_ccy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quote_ccy', to='swpm.Ccy')),
            ],
        ),
        migrations.CreateModel(
            name='FXO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('trade_date', models.DateField()),
                ('maturity_date', models.DateField()),
                ('strike_price', models.DecimalField(decimal_places=8, max_digits=8)),
                ('notional_1', models.DecimalField(decimal_places=2, max_digits=2)),
                ('notional_2', models.DecimalField(decimal_places=2, max_digits=2)),
                ('type', models.CharField(choices=[('EUR', 'European'), ('AME', 'American'), ('DIG', 'Digital'), ('BAR', 'Barrier')], max_length=5)),
                ('cp', models.CharField(choices=[('C', 'Call'), ('P', 'Put')], max_length=1)),
                ('ccypair', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='swpm.CcyPair')),
            ],
        ),
    ]
