# Generated by Django 2.2.5 on 2021-11-04 13:06

import datetime
from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import swpm.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0013_auto_20211001_1456'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('name', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='books', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Ccy',
            fields=[
                ('code', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('fixing_days', models.PositiveIntegerField(default=2)),
                ('cdr', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ccys', to='swpm.Calendar')),
            ],
        ),
        migrations.CreateModel(
            name='CcyPair',
            fields=[
                ('name', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('fixing_days', models.PositiveIntegerField(default=2)),
                ('base_ccy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='as_base_ccy', to='swpm.Ccy')),
                ('cdr', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ccy_pairs', to='swpm.Calendar')),
                ('quote_ccy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='as_quote_ccy', to='swpm.Ccy')),
            ],
        ),
        migrations.CreateModel(
            name='Counterparty',
            fields=[
                ('code', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('is_internal', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='internal_cpty', to='swpm.Book')),
            ],
            options={
                'verbose_name_plural': 'Counterparties',
            },
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('name', models.CharField(max_length=16, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='RateIndex',
            fields=[
                ('name', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('ccy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rate_indexs', to='swpm.Ccy')),
            ],
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('trade_date', models.DateField()),
                ('book', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trades', to='swpm.Book')),
                ('counterparty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='trade_set', to='swpm.Counterparty')),
            ],
        ),
        migrations.CreateModel(
            name='TradeDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Swap',
            fields=[
                ('trade_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='swpm.Trade')),
            ],
            bases=('swpm.trade',),
        ),
        migrations.AddField(
            model_name='trade',
            name='detail',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trade', to='swpm.TradeDetail'),
        ),
        migrations.AddField(
            model_name='trade',
            name='input_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='input_trades', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='RateQuote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
                ('ref_date', models.DateField()),
                ('rate', models.FloatField()),
                ('tenor', models.CharField(max_length=5)),
                ('instrument', models.CharField(max_length=5)),
                ('day_counter', models.CharField(max_length=16)),
                ('ccy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='swpm.Ccy')),
            ],
        ),
        migrations.CreateModel(
            name='IRTermStructure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
                ('ref_date', models.DateField()),
                ('as_fx_curve', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fx_curve', to='swpm.Ccy')),
                ('as_rf_curve', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rf_curve', to='swpm.Ccy')),
                ('rates', models.ManyToManyField(related_name='ts', to='swpm.RateQuote')),
            ],
        ),
        migrations.CreateModel(
            name='FXVolatility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_date', models.DateField()),
                ('vol', models.FloatField()),
                ('ccy_pair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vol', to='swpm.CcyPair')),
            ],
            options={
                'verbose_name_plural': 'FX volatilities',
            },
        ),
        migrations.AddField(
            model_name='book',
            name='portfolio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='books', to='swpm.Portfolio'),
        ),
        migrations.CreateModel(
            name='TradeMarkToMarket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('as_of', models.DateField()),
                ('npv', models.FloatField(null=True)),
                ('delta', models.FloatField(null=True)),
                ('gamma', models.FloatField(null=True)),
                ('vega', models.FloatField(null=True)),
                ('trade_d', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mtms', to='swpm.TradeDetail')),
            ],
            options={
                'unique_together': {('as_of', 'trade_d')},
            },
        ),
        migrations.CreateModel(
            name='SwapLeg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effective_date', models.DateField(default=datetime.date(2021, 11, 4))),
                ('maturity_date', models.DateField(default=datetime.date(2021, 11, 4))),
                ('notional', models.FloatField()),
                ('pay_rec', models.IntegerField(choices=[(1, 'Recive'), (-1, 'Pay')])),
                ('fixed_rate', models.FloatField(blank=True, default=0, null=True)),
                ('spread', models.FloatField(default=0, null=True)),
                ('reset_freq', models.CharField(blank=True, max_length=10, null=True)),
                ('payment_freq', models.CharField(max_length=16)),
                ('day_counter', models.CharField(choices=[('A360', 'A360'), ('A365Fixed', 'A365Fixed')], max_length=16)),
                ('ccy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swap_legs', to='swpm.Ccy')),
                ('index', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='swpm.RateIndex')),
                ('trade', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='legs', to='swpm.Swap')),
            ],
        ),
        migrations.CreateModel(
            name='FxSpotRateQuote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_date', models.DateField()),
                ('rate', models.FloatField()),
                ('ccy_pair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='swpm.CcyPair')),
            ],
            options={
                'unique_together': {('ref_date', 'ccy_pair')},
            },
        ),
        migrations.CreateModel(
            name='FXO',
            fields=[
                ('trade_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='swpm.Trade')),
                ('maturity_date', models.DateField(default=datetime.date(2021, 11, 4))),
                ('buy_sell', models.CharField(choices=[('B', 'Buy'), ('S', 'Sell')], max_length=1)),
                ('strike_price', models.FloatField(validators=[swpm.models.validate_positive])),
                ('notional_1', models.FloatField(validators=[swpm.models.validate_positive])),
                ('notional_2', models.FloatField(validators=[swpm.models.validate_positive])),
                ('type', models.CharField(choices=[('EUR', 'European'), ('AME', 'American'), ('DIG', 'Digital'), ('BAR', 'Barrier')], max_length=5)),
                ('cp', models.CharField(choices=[('C', 'Call'), ('P', 'Put')], max_length=1)),
                ('ccy_pair', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='options', to='swpm.CcyPair')),
            ],
            bases=('swpm.trade',),
        ),
    ]
