# Generated by Django 3.2.9 on 2021-11-19 02:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swpm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ccy',
            name='rate_day_counter',
            field=models.CharField(blank=True, default=None, max_length=24, null=True),
        ),
        migrations.AlterField(
            model_name='fxo',
            name='maturity_date',
            field=models.DateField(default=datetime.date(2021, 11, 19)),
        ),
        migrations.AlterField(
            model_name='swapleg',
            name='effective_date',
            field=models.DateField(default=datetime.date(2021, 11, 19)),
        ),
    ]
