# Generated by Django 2.2.5 on 2021-11-03 15:38

from django.db import migrations, models
import django.db.models.deletion
import swpm.models


class Migration(migrations.Migration):

    dependencies = [
        ('swpm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counterparty',
            name='is_internal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='internal_cpty', to='swpm.Book'),
        ),
        migrations.AlterField(
            model_name='fxo',
            name='notional_1',
            field=models.FloatField(validators=[swpm.models.validate_positive]),
        ),
        migrations.AlterField(
            model_name='fxo',
            name='notional_2',
            field=models.FloatField(validators=[swpm.models.validate_positive]),
        ),
        migrations.AlterField(
            model_name='fxo',
            name='strike_price',
            field=models.FloatField(validators=[swpm.models.validate_positive]),
        ),
    ]
