# Generated by Django 3.2.8 on 2021-11-06 04:37

import datetime
import django.core.validators
from django.db import migrations, models
import swpm.models


class Migration(migrations.Migration):

    dependencies = [
        ('swpm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fxo',
            name='maturity_date',
            field=models.DateField(default=datetime.date(2021, 11, 6)),
        ),
        migrations.AlterField(
            model_name='fxo',
            name='notional_1',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.01), django.core.validators.DecimalValidator(decimal_places=2, max_digits=20)]),
        ),
        migrations.AlterField(
            model_name='swapleg',
            name='effective_date',
            field=models.DateField(default=datetime.date(2021, 11, 6)),
        ),
        migrations.AlterField(
            model_name='swapleg',
            name='maturity_date',
            field=models.DateField(default=datetime.date(2021, 11, 6)),
        ),
        migrations.AlterField(
            model_name='swapleg',
            name='notional',
            field=models.FloatField(default=1000000, validators=[swpm.models.validate_positive]),
        ),
        migrations.AlterField(
            model_name='swapleg',
            name='payment_freq',
            field=models.CharField(max_length=16, validators=[django.core.validators.RegexValidator]),
        ),
        migrations.AlterField(
            model_name='swapleg',
            name='reset_freq',
            field=models.CharField(blank=True, max_length=16, null=True, validators=[django.core.validators.RegexValidator]),
        ),
    ]
