# Generated by Django 3.2.8 on 2021-10-31 07:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swpm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratequote',
            name='ref_date',
            field=models.DateField(default=datetime.date(2021, 10, 31)),
            preserve_default=False,
        ),
    ]
