# Generated by Django 3.2.8 on 2021-10-24 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swpm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fxo',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
