# Generated by Django 3.2.8 on 2021-10-31 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swpm', '0002_ratequote_ref_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='fxo',
            name='buy_sell',
            field=models.CharField(default='B', max_length=1),
            preserve_default=False,
        ),
    ]
