# Generated by Django 3.2.8 on 2021-10-24 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('swpm', '0002_alter_fxo_create_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fxo',
            name='ccypair',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='options', to='swpm.ccypair'),
        ),
        migrations.AlterField(
            model_name='fxo',
            name='notional_1',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='fxo',
            name='notional_2',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='fxo',
            name='strike_price',
            field=models.FloatField(),
        ),
    ]
