# Generated by Django 2.2.5 on 2021-11-03 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('swpm', '0002_auto_20211103_2338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counterparty',
            name='is_internal',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='internal_cpty', to='swpm.Book'),
        ),
    ]
