# Generated by Django 3.2.8 on 2021-11-06 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swpm', '0002_auto_20211106_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fxo',
            name='notional_1',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='fxo',
            name='notional_2',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='fxo',
            name='strike_price',
            field=models.FloatField(),
        ),
    ]
