# Generated by Django 3.2.9 on 2021-11-19 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swpm', '0003_auto_20211119_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='swapleg',
            name='tenor',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
