# Generated by Django 3.2.8 on 2021-10-31 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swpm', '0003_fxo_buy_sell'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fxo',
            name='buy_sell',
            field=models.CharField(choices=[('B', 'Buy'), ('S', 'Sell')], max_length=1),
        ),
    ]
