# Generated by Django 2.2.5 on 2021-10-26 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('swpm', '0004_auto_20211026_2226'),
    ]

    operations = [
        migrations.AddField(
            model_name='ccy',
            name='cdr',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ccy', to='swpm.Calendar'),
        ),
    ]
