# Generated by Django 2.2.5 on 2021-10-31 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('swpm', '0004_alter_fxo_buy_sell'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradedetail',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='trades', to='swpm.Book'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, verbose_name='first name'),
        ),
    ]
