# Generated by Django 3.2.8 on 2021-11-06 07:42

from django.db import migrations, models
import swpm.models


class Migration(migrations.Migration):

    dependencies = [
        ('swpm', '0004_auto_20211106_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fxo',
            name='strike_price',
            field=models.FloatField(validators=[swpm.models.validate_positive]),
        ),
    ]
