# Generated by Django 2.2.5 on 2021-10-26 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('swpm', '0005_ccy_cdr'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ratequote',
            old_name='type',
            new_name='instrument',
        ),
    ]
