# Generated by Django 3.2.9 on 2021-11-20 02:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('swpm', '0005_auto_20211120_1020'),
    ]

    operations = [
        migrations.AddField(
            model_name='ccypair',
            name='calendar',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ccy_pairs', to='swpm.calendar'),
        ),
    ]
