# Generated by Django 3.2.8 on 2021-10-31 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('swpm', '0005_auto_20211031_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='trademarktomarket',
            name='delta',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='trademarktomarket',
            name='gamma',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='trademarktomarket',
            name='npv',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='trademarktomarket',
            name='trade_d',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mtms', to='swpm.tradedetail'),
        ),
        migrations.AddField(
            model_name='trademarktomarket',
            name='vega',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
        migrations.AlterUniqueTogether(
            name='trademarktomarket',
            unique_together={('as_of', 'trade_d')},
        ),
        migrations.RemoveField(
            model_name='trademarktomarket',
            name='trade',
        ),
    ]
