# Generated by Django 3.2.8 on 2021-11-06 07:43

from django.db import migrations, models
import swpm.models


class Migration(migrations.Migration):

    dependencies = [
        ('swpm', '0005_alter_fxo_strike_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fxo',
            name='notional_1',
            field=models.FloatField(validators=[swpm.models.validate_positive]),
        ),
        migrations.AlterField(
            model_name='fxo',
            name='notional_2',
            field=models.FloatField(validators=[swpm.models.validate_positive]),
        ),
    ]
