# Generated by Django 2.2.5 on 2021-10-27 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('swpm', '0006_auto_20211026_2311'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fxo',
            name='ccypair',
        ),
        migrations.AddField(
            model_name='fxo',
            name='ccy_pair',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='options', to='swpm.CcyPair'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='FxSpotRateQuote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_date', models.DateField()),
                ('rate', models.FloatField()),
                ('ccy_pair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rate', to='swpm.CcyPair')),
            ],
        ),
    ]
