# Generated by Django 2.2.5 on 2021-11-01 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swpm', '0006_auto_20211031_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, verbose_name='first name'),
        ),
    ]
