# Generated by Django 3.2.9 on 2021-11-06 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swpm', '0007_alter_swapleg_trade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='swapleg',
            name='spread',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
