# Generated by Django 2.2.5 on 2021-11-01 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('swpm', '0007_auto_20211101_2054'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fxo',
            options={'ordering': ['id']},
        ),
    ]
