# Generated by Django 3.2.9 on 2021-11-21 06:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swpm', '0007_auto_20211120_1218'),
    ]

    operations = [
    ]
