# Generated by Django 3.2.9 on 2021-11-07 08:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swpm', '0008_alter_swapleg_spread'),
    ]

    operations = [
        migrations.AddField(
            model_name='rateindex',
            name='yts',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='fxo',
            name='maturity_date',
            field=models.DateField(default=datetime.date(2021, 11, 7)),
        ),
        migrations.AlterField(
            model_name='swapleg',
            name='effective_date',
            field=models.DateField(default=datetime.date(2021, 11, 7)),
        ),
        migrations.AlterField(
            model_name='swapleg',
            name='maturity_date',
            field=models.DateField(default=datetime.date(2021, 11, 7)),
        ),
        migrations.AlterUniqueTogether(
            name='irtermstructure',
            unique_together={('name', 'ref_date')},
        ),
    ]
