# Generated by Django 3.2.9 on 2021-11-21 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swpm', '0008_auto_20211121_1448'),
    ]

    operations = [
    ]
