# Generated by Django 2.2.5 on 2021-11-01 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('swpm', '0008_auto_20211101_2143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tradedetail',
            name='trade',
        ),
        migrations.AddField(
            model_name='fxo',
            name='detail',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trade', to='swpm.TradeDetail'),
        ),
    ]
