# Generated by Django 2.2.5 on 2021-10-28 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('swpm', '0008_auto_20211027_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='irtermstructure',
            name='as_fx_curve',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fx_curve', to='swpm.Ccy'),
        ),
        migrations.AlterField(
            model_name='irtermstructure',
            name='as_rf_curve',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rf_curve', to='swpm.Ccy'),
        ),
    ]
