# Generated by Django 2.2.5 on 2021-10-29 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('swpm', '0009_auto_20211028_2203'),
    ]

    operations = [
        migrations.AddField(
            model_name='ccypair',
            name='fixing_days',
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='ccy',
            name='cdr',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ccys', to='swpm.Calendar'),
        ),
        migrations.AlterField(
            model_name='ccypair',
            name='cdr',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ccy_pairs', to='swpm.Calendar'),
        ),
        migrations.AlterField(
            model_name='fxspotratequote',
            name='ccy_pair',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='swpm.CcyPair'),
        ),
        migrations.AlterField(
            model_name='ratequote',
            name='day_counter',
            field=models.CharField(max_length=16),
        ),
    ]
