# Generated by Django 3.2.9 on 2021-11-08 13:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swpm', '0009_auto_20211107_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fxo',
            name='maturity_date',
            field=models.DateField(default=datetime.date(2021, 11, 8)),
        ),
        migrations.AlterField(
            model_name='rateindex',
            name='day_counter',
            field=models.CharField(blank=True, choices=[('Actual360', 'Actual360'), ('Actual365Fixed', 'Actual365Fixed'), ('ActualActual', 'Actualactual'), ('Thirty360', 'Thirty360')], max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='swapleg',
            name='effective_date',
            field=models.DateField(default=datetime.date(2021, 11, 8)),
        ),
        migrations.AlterField(
            model_name='swapleg',
            name='maturity_date',
            field=models.DateField(default=datetime.date(2021, 11, 8)),
        ),
    ]
