# Generated by Django 2.2.5 on 2021-11-01 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('swpm', '0009_auto_20211101_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradedetail',
            name='book',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='trades', to='swpm.Book'),
        ),
    ]
