# Generated by Django 3.2.9 on 2021-11-21 06:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('swpm', '0009_alter_fxo_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fxo',
            name='maturity_date',
            field=models.DateField(default=datetime.datetime(2021, 11, 21, 6, 53, 33, 240180, tzinfo=utc)),
        ),
    ]
