# Generated by Django 3.2.9 on 2021-11-21 06:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('swpm', '0010_alter_fxo_maturity_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fxo',
            name='maturity_date',
            field=models.DateField(default=datetime.datetime(2021, 11, 21, 6, 54, 39, 417563, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='swapleg',
            name='effective_date',
            field=models.DateField(default=datetime.date(2021, 11, 21)),
        ),
    ]
