# Generated by Django 3.2.9 on 2021-11-09 12:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swpm', '0011_auto_20211108_2247'),
    ]

    operations = [
        migrations.AddField(
            model_name='swap',
            name='maturity_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fxo',
            name='maturity_date',
            field=models.DateField(default=datetime.date(2021, 11, 9)),
        ),
        migrations.AlterField(
            model_name='swapleg',
            name='effective_date',
            field=models.DateField(default=datetime.date(2021, 11, 9)),
        ),
        migrations.AlterField(
            model_name='swapleg',
            name='maturity_date',
            field=models.DateField(),
        ),
    ]
