# Generated by Django 3.2.9 on 2021-11-21 06:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swpm', '0011_auto_20211121_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fxo',
            name='maturity_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
