# Generated by Django 3.2.9 on 2021-11-21 07:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swpm', '0012_alter_fxo_maturity_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='swapleg',
            name='effective_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
