# Generated by Django 3.2.9 on 2021-11-21 07:12

from django.db import migrations, models
import django.db.models.deletion
import swpm.models


class Migration(migrations.Migration):

    dependencies = [
        ('swpm', '0013_alter_swapleg_effective_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fxo',
            name='notional_1',
            field=models.FloatField(default=1000000.0, validators=[swpm.models.validate_positive]),
        ),
        migrations.AlterField(
            model_name='swapleg',
            name='ccy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='swpm.ccy'),
        ),
    ]
