# Generated by Django 3.2.9 on 2021-11-21 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('swpm', '0014_auto_20211121_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='pl_ccy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='swpm.ccy'),
        ),
    ]
