# Generated by Django 3.2.9 on 2021-11-13 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('swpm', '0015_auto_20211113_1111'),
        ('swpm', '0015_auto_20211113_1628'),
    ]

    operations = [
    ]
