# Generated by Django 3.2.9 on 2021-11-14 11:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swpm', '0015_auto_20211113_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fxo',
            name='maturity_date',
            field=models.DateField(default=datetime.date(2021, 11, 14)),
        ),
        migrations.AlterField(
            model_name='swapleg',
            name='effective_date',
            field=models.DateField(default=datetime.date(2021, 11, 14)),
        ),
        migrations.AlterField(
            model_name='swapleg',
            name='fixed_rate',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
