# Generated by Django 3.2.9 on 2021-11-21 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('swpm', '0015_trade_pl_ccy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='detail',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='swpm.tradedetail'),
        ),
    ]
