# Generated by Django 3.2.9 on 2021-11-21 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('swpm', '0016_alter_trade_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='counterparty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trade_set', to='swpm.counterparty'),
        ),
        migrations.CreateModel(
            name='CashFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default=0)),
                ('ccy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='swpm.ccy')),
                ('trade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='swpm.trade')),
            ],
        ),
    ]
