# Generated by Django 3.2.9 on 2021-11-14 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('swpm', '0016_auto_20211114_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='swapleg',
            name='calendar',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='swpm.calendar'),
            preserve_default=False,
        ),
    ]
