# Generated by Django 3.2.9 on 2021-11-15 14:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swpm', '0017_alter_swapleg_calendar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fxo',
            name='maturity_date',
            field=models.DateField(default=datetime.date(2021, 11, 15)),
        ),
        migrations.AlterField(
            model_name='swapleg',
            name='effective_date',
            field=models.DateField(default=datetime.date(2021, 11, 15)),
        ),
        migrations.AlterUniqueTogether(
            name='irtermstructure',
            unique_together={('name', 'ref_date', 'ccy')},
        ),
    ]
