# Generated by Django 3.2.9 on 2021-11-16 12:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swpm', '0018_auto_20211115_2222'),
    ]

    operations = [
        migrations.AddField(
            model_name='fxo',
            name='product_type',
            field=models.CharField(default='FXO', max_length=12),
        ),
        migrations.AddField(
            model_name='swap',
            name='product_type',
            field=models.CharField(default='SWAP', max_length=12),
        ),
        migrations.AlterField(
            model_name='fxo',
            name='maturity_date',
            field=models.DateField(default=datetime.date(2021, 11, 16)),
        ),
        migrations.AlterField(
            model_name='swapleg',
            name='effective_date',
            field=models.DateField(default=datetime.date(2021, 11, 16)),
        ),
    ]
