# Generated by Django 3.2.9 on 2021-12-22 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swpm', '0019_alter_fxvolatilityquote_t'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fxvolatilityquote',
            name='t',
            field=models.DateField(blank=True, null=True),
        ),
    ]
