# Generated by Django 3.2.9 on 2021-11-17 14:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swpm', '0019_auto_20211116_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fxo',
            name='maturity_date',
            field=models.DateField(default=datetime.date(2021, 11, 17)),
        ),
        migrations.AlterField(
            model_name='swapleg',
            name='effective_date',
            field=models.DateField(default=datetime.date(2021, 11, 17)),
        ),
    ]
