# Generated by Django 3.2.9 on 2021-11-18 00:20

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('swpm', '0020_auto_20211117_2226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calendar',
            name='id',
        ),
        migrations.AddField(
            model_name='swapleg',
            name='day_rule',
            field=models.CharField(choices=[('Following', 'Following'), ('ModifiedFollowing', 'Modifiedfollowing'), ('Preceding', 'Preceding'), ('ModifiedPreceding', 'Modifiedpreceding'), ('Unadjusted', 'Unadjusted')], default='ModifiedFollowing', max_length=24),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='name',
            field=models.CharField(max_length=24, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='fxo',
            name='maturity_date',
            field=models.DateField(default=datetime.date(2021, 11, 18)),
        ),
        migrations.AlterField(
            model_name='swapleg',
            name='calendar',
            field=models.ForeignKey(default='HongKong', on_delete=django.db.models.deletion.SET_DEFAULT, to='swpm.calendar'),
        ),
        migrations.AlterField(
            model_name='swapleg',
            name='effective_date',
            field=models.DateField(default=datetime.date(2021, 11, 18)),
        ),
        migrations.AlterUniqueTogether(
            name='rateindex',
            unique_together={('name', 'tenor')},
        ),
    ]
