# Generated by Django 3.2.9 on 2021-12-24 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swpm', '0020_alter_fxvolatilityquote_t'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fxvolatilityquote',
            old_name='t',
            new_name='maturity',
        ),
        migrations.AddField(
            model_name='fxvolatilityquote',
            name='delta_type',
            field=models.CharField(choices=[('Spot', 'Spot'), ('PaSpot', 'Paspot'), ('Fwd', 'Fwd'), ('PaFwd', 'Pafwd')], max_length=8, null=True),
        ),
    ]
