# Generated by Django 3.2.9 on 2021-11-18 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('swpm', '0021_auto_20211118_0820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='swapleg',
            name='calendar',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='swpm.calendar'),
        ),
    ]
