# Generated by Django 3.2.9 on 2021-12-28 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('swpm', '0022_auto_20211227_1734'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ccy',
            old_name='calendar',
            new_name='cal',
        ),
        migrations.RenameField(
            model_name='ccypair',
            old_name='calendar',
            new_name='cal',
        ),
        migrations.AlterUniqueTogether(
            name='ratequote',
            unique_together={('name', 'tenor', 'ref_date')},
        ),
    ]
