# Generated by Django 3.2.9 on 2021-12-30 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swpm', '0024_ratequote_ccy_pair'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratequote',
            name='day_counter',
            field=models.CharField(blank=True, choices=[('Actual360', 'Actual360'), ('Actual365Fixed', 'Actual365Fixed'), ('ActualActual', 'Actualactual'), ('Thirty360', 'Thirty360')], max_length=16, null=True),
        ),
    ]
