# Generated by Django 3.2.9 on 2021-12-30 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('swpm', '0025_alter_ratequote_day_counter'),
    ]

    operations = [
        migrations.AddField(
            model_name='irtermstructure',
            name='ref_ccy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='swpm.ccy'),
        ),
    ]
