# Generated by Django 3.2.9 on 2022-01-02 05:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('swpm', '0026_irtermstructure_ref_ccy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fxo',
            name='ccy_pair',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='swpm.ccypair'),
        ),
    ]
