# Generated by Django 3.2.9 on 2022-01-16 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('swpm', '0027_alter_fxo_ccy_pair'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ccy',
            name='cal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='swpm.calendar'),
        ),
        migrations.AlterField(
            model_name='ccypair',
            name='cal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ccy_pairs', to='swpm.calendar'),
        ),
    ]
