# Generated by Django 3.2.9 on 2022-01-26 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swpm', '0028_auto_20220116_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fxvolatilityquote',
            name='delta',
            field=models.FloatField(error_messages={'required': 'Delta value is required.'}),
        ),
    ]
