# Generated by Django 3.2.9 on 2022-02-03 13:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swpm', '0031_alter_fxspotratequote_ccy_pair'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='value_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='fxo',
            name='maturity_date',
            field=models.DateField(),
        ),
    ]
