# Generated by Django 3.2.9 on 2022-02-03 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('swpm', '0032_auto_20220203_2138'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fxo',
            old_name='type',
            new_name='payoff_type',
        ),
    ]
