# Generated by Django 3.2.9 on 2022-02-03 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swpm', '0033_rename_type_fxo_payoff_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='fxo',
            name='exercise_type',
            field=models.CharField(choices=[('EUR', 'European'), ('AME', 'American'), ('DIG', 'Digital'), ('BAR', 'Barrier')], max_length=5, null=True),
        ),
    ]
