# Generated by Django 3.2.9 on 2022-02-06 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('swpm', '0035_auto_20220206_1310'),
    ]

    operations = [
        migrations.CreateModel(
            name='BarrierDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barrier_start', models.DateField(blank=True, null=True)),
                ('barrier_end', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='fxo',
            name='barrier_end',
        ),
        migrations.RemoveField(
            model_name='fxo',
            name='barrier_start',
        ),
        migrations.AddField(
            model_name='fxo',
            name='barrier',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='fxo',
            name='exercise_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fxo',
            name='exercise_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fxo',
            name='barrier_detail',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='swpm.barrierdetail'),
        ),
    ]
