# Generated by Django 3.2.9 on 2022-02-07 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('swpm', '0036_auto_20220206_1638'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fxvolatilityquote',
            old_name='vol',
            new_name='value',
        ),
    ]
