# Generated by Django 3.2.9 on 2022-02-08 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('swpm', '0039_auto_20220208_2105'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ccy',
            name='fx_curve',
        ),
        migrations.RemoveField(
            model_name='ccy',
            name='rf_curve',
        ),
        migrations.AddField(
            model_name='ccy',
            name='foreign_exchange_curve',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='ccy',
            name='risk_free_curve',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='irtermstructure',
            name='as_fx_curve',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fx_curve', to='swpm.ccy'),
        ),
        migrations.AddField(
            model_name='irtermstructure',
            name='as_rf_curve',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rf_curve', to='swpm.ccy'),
        ),
    ]
