# Generated by Django 3.2.9 on 2022-02-09 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swpm', '0040_auto_20220208_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interestratequote',
            name='rate',
            field=models.DecimalField(decimal_places=8, max_digits=12),
        ),
    ]
