# Generated by Django 3.2.9 on 2022-02-09 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('swpm', '0041_alter_interestratequote_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='irtermstructure',
            name='rates',
        ),
        migrations.AddField(
            model_name='interestratequote',
            name='yts',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='swpm.irtermstructure'),
        ),
    ]
