# Generated by Django 3.2.9 on 2022-02-12 07:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swpm', '0043_auto_20220212_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashflow',
            name='value_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
