# Generated by Django 3.2.9 on 2022-02-12 09:56

from django.db import migrations, models
import django.db.models.deletion
import swpm.models


class Migration(migrations.Migration):

    dependencies = [
        ('swpm', '0044_alter_cashflow_value_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fxo',
            name='barrier_detail',
        ),
        migrations.AddField(
            model_name='fxobarrierdetail',
            name='rebate_ccy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='swpm.ccy'),
        ),
        migrations.AlterField(
            model_name='cashflow',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=32, null=True),
        ),
        migrations.AlterField(
            model_name='cashflow',
            name='ccy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='swpm.ccy'),
        ),
        migrations.AlterField(
            model_name='fxobarrierdetail',
            name='id',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='swpm.fxo'),
        ),
        migrations.AlterField(
            model_name='fxobarrierdetail',
            name='lower_barrier_level',
            field=models.FloatField(blank=True, null=True, validators=[swpm.models.validate_positive]),
        ),
        migrations.AlterField(
            model_name='fxobarrierdetail',
            name='upper_barrier_level',
            field=models.FloatField(blank=True, null=True, validators=[swpm.models.validate_positive]),
        ),
    ]
