# Generated by Django 3.2.9 on 2022-02-12 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('swpm', '0045_auto_20220212_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fxobarrierdetail',
            name='id',
            field=models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='swpm.fxo'),
        ),
    ]
