# Generated by Django 3.2.9 on 2022-02-12 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('swpm', '0046_alter_fxobarrierdetail_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashflow',
            name='cashflow_type',
            field=models.TextField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='cashflow',
            name='trade',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='cashflows', to='swpm.trade'),
        ),
    ]
