# Generated by Django 3.2.9 on 2022-02-12 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swpm', '0047_auto_20220212_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashflow',
            name='cashflow_type',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
