# Generated by Django 3.2.9 on 2022-02-12 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swpm', '0048_alter_cashflow_cashflow_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fxobarrierdetail',
            old_name='lower_barrier_level',
            new_name='lower_barrier',
        ),
        migrations.RenameField(
            model_name='fxobarrierdetail',
            old_name='upper_barrier_level',
            new_name='upper_barrier',
        ),
        migrations.AlterField(
            model_name='fxo',
            name='payoff_type',
            field=models.CharField(choices=[('VAN', 'Vanilla'), ('DIG', 'Digital')], max_length=5),
        ),
    ]
