# Generated by Django 3.2.9 on 2022-02-12 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swpm', '0049_auto_20220212_2245'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fxobarrierdetail',
            old_name='id',
            new_name='trade',
        ),
        migrations.AlterField(
            model_name='fxobarrierdetail',
            name='rebate',
            field=models.DecimalField(decimal_places=2, max_digits=24),
        ),
    ]
