# Generated by Django 3.2.9 on 2022-02-12 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('swpm', '0050_auto_20220212_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fxobarrierdetail',
            name='trade',
            field=models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='barrier_detail', serialize=False, to='swpm.fxo'),
        ),
    ]
