# Generated by Django 3.2.9 on 2022-02-12 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('swpm', '0051_alter_fxobarrierdetail_trade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fxobarrierdetail',
            name='rebate_ccy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='swpm.ccy'),
        ),
    ]
