# Generated by Django 3.2.9 on 2022-02-13 06:17

from django.db import migrations, models
import django.db.models.deletion
import swpm.models


class Migration(migrations.Migration):

    dependencies = [
        ('swpm', '0052_alter_fxobarrierdetail_rebate_ccy'),
    ]

    operations = [
        migrations.CreateModel(
            name='FXOLowerBarrierDetail',
            fields=[
                ('barrier_start', models.DateField(blank=True, null=True)),
                ('barrier_end', models.DateField(blank=True, null=True)),
                ('barrier', models.FloatField(blank=True, null=True, validators=[swpm.models.validate_positive])),
                ('rebate', models.DecimalField(decimal_places=2, max_digits=24)),
                ('rebate_at_hit', models.BooleanField(default=False)),
                ('payoff_at_hit', models.BooleanField(default=False)),
                ('trade', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='lower_barrier_detail', serialize=False, to='swpm.fxo')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FXOUpperBarrierDetail',
            fields=[
                ('barrier_start', models.DateField(blank=True, null=True)),
                ('barrier_end', models.DateField(blank=True, null=True)),
                ('barrier', models.FloatField(blank=True, null=True, validators=[swpm.models.validate_positive])),
                ('rebate', models.DecimalField(decimal_places=2, max_digits=24)),
                ('rebate_at_hit', models.BooleanField(default=False)),
                ('payoff_at_hit', models.BooleanField(default=False)),
                ('trade', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='upper_barrier_detail', serialize=False, to='swpm.fxo')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='fxo',
            name='ccy_pair',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='swpm.ccypair'),
        ),
        migrations.AlterField(
            model_name='interestratequote',
            name='ccy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ir_quotes', to='swpm.ccy'),
        ),
        migrations.DeleteModel(
            name='FXOBarrierDetail',
        ),
    ]
