# Generated by Django 3.2.9 on 2022-02-13 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('swpm', '0053_auto_20220213_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='fxolowerbarrierdetail',
            name='rebate_ccy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='swpm.ccy'),
        ),
        migrations.AddField(
            model_name='fxoupperbarrierdetail',
            name='rebate_ccy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='swpm.ccy'),
        ),
    ]
