# Generated by Django 3.2.9 on 2022-02-13 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swpm', '0054_auto_20220213_1419'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fxolowerbarrierdetail',
            name='barrier_end',
        ),
        migrations.RemoveField(
            model_name='fxolowerbarrierdetail',
            name='barrier_start',
        ),
        migrations.RemoveField(
            model_name='fxoupperbarrierdetail',
            name='barrier_end',
        ),
        migrations.RemoveField(
            model_name='fxoupperbarrierdetail',
            name='barrier_start',
        ),
        migrations.AddField(
            model_name='fxolowerbarrierdetail',
            name='knock',
            field=models.CharField(blank=True, choices=[('IN', 'IN'), ('OUT', 'OUT')], max_length=3),
        ),
        migrations.AddField(
            model_name='fxoupperbarrierdetail',
            name='knock',
            field=models.CharField(blank=True, choices=[('IN', 'IN'), ('OUT', 'OUT')], max_length=3),
        ),
        migrations.AlterField(
            model_name='fxo',
            name='payoff_type',
            field=models.CharField(choices=[('PLA', 'Plain'), ('DIG', 'Digital')], max_length=5),
        ),
        migrations.AlterField(
            model_name='fxolowerbarrierdetail',
            name='rebate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=24),
        ),
        migrations.AlterField(
            model_name='fxoupperbarrierdetail',
            name='rebate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=24),
        ),
    ]
