# Generated by Django 3.2.9 on 2022-02-20 06:42

import datetime
from django.db import migrations, models
import django.db.models.deletion
import swpm.models


class Migration(migrations.Migration):

    dependencies = [
        ('swpm', '0056_fxo_subtype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Swaption',
            fields=[
                ('trade_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='swpm.trade')),
                ('product_type', models.CharField(default='SWAPTION', max_length=12)),
                ('exercise_date', models.DateField()),
                ('buy_sell', models.CharField(choices=[('B', 'Buy'), ('S', 'Sell')], default='B', max_length=1)),
            ],
            bases=('swpm.trade',),
        ),
        migrations.CreateModel(
            name='VanillaSwap',
            fields=[
                ('trade_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='swpm.trade')),
                ('product_type', models.CharField(default='SWAP', max_length=12)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('maturity_date', models.DateField(blank=True, null=True)),
                ('notional', models.DecimalField(decimal_places=2, default=1000000.0, max_digits=24, validators=[swpm.models.validate_positive])),
            ],
            bases=('swpm.trade',),
        ),
        migrations.RemoveField(
            model_name='swapleg',
            name='calendar',
        ),
        migrations.RemoveField(
            model_name='swapleg',
            name='day_rule',
        ),
        migrations.RemoveField(
            model_name='swapleg',
            name='effective_date',
        ),
        migrations.RemoveField(
            model_name='swapleg',
            name='maturity_date',
        ),
        migrations.RemoveField(
            model_name='swapleg',
            name='payment_freq',
        ),
        migrations.RemoveField(
            model_name='swapleg',
            name='reset_freq',
        ),
        migrations.AlterField(
            model_name='swapleg',
            name='fixed_rate',
            field=models.DecimalField(decimal_places=8, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='swapleg',
            name='index',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='swpm.rateindex'),
        ),
        migrations.AlterField(
            model_name='swapleg',
            name='notional',
            field=models.DecimalField(decimal_places=8, max_digits=10, validators=[swpm.models.validate_positive]),
        ),
        migrations.AlterField(
            model_name='swapleg',
            name='spread',
            field=models.DecimalField(decimal_places=8, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='swapleg',
            name='tenor',
            field=models.CharField(blank=True, max_length=8, null=True, validators=[swpm.models.validate_period]),
        ),
        migrations.AlterField(
            model_name='swapleg',
            name='trade',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='legs', to='swpm.swap'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effective_date', models.DateField(default=datetime.date.today)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('freq', models.CharField(blank=True, max_length=16, null=True, validators=[swpm.models.validate_period])),
                ('day_rule', models.CharField(choices=[('Following', 'Following'), ('ModifiedFollowing', 'Modifiedfollowing'), ('Preceding', 'Preceding'), ('ModifiedPreceding', 'Modifiedpreceding'), ('Unadjusted', 'Unadjusted')], default='ModifiedFollowing', max_length=24)),
                ('calendar', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='swpm.calendar')),
            ],
        ),
        migrations.AddField(
            model_name='swapleg',
            name='schedule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='swpm.schedule'),
        ),
    ]
