# Generated by Django 3.2.9 on 2022-02-20 08:35

from django.db import migrations, models
import django.db.models.deletion
import swpm.models


class Migration(migrations.Migration):

    dependencies = [
        ('swpm', '0059_auto_20220220_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interestratequote',
            name='yts',
            field=models.ForeignKey(blank=True, limit_choices_to=swpm.models.InterestRateQuote.limit_choices_yts, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='swpm.irtermstructure'),
        ),
    ]
