# Generated by Django 3.2.9 on 2022-02-20 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('swpm', '0060_alter_interestratequote_yts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interestratequote',
            name='yts',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='swpm.irtermstructure'),
        ),
    ]
