# Generated by Django 3.2.9 on 2022-02-20 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('swpm', '0061_alter_interestratequote_yts'),
    ]

    operations = [
        migrations.AddField(
            model_name='interestratequote',
            name='index',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='quotes', to='swpm.rateindex'),
        ),
        migrations.AlterUniqueTogether(
            name='interestratequote',
            unique_together={('name', 'ref_date')},
        ),
    ]
