# Generated by Django 3.2.9 on 2022-02-20 10:23

from django.db import migrations, models
import swpm.models


class Migration(migrations.Migration):

    dependencies = [
        ('swpm', '0062_auto_20220220_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='swapleg',
            name='notional',
            field=models.DecimalField(decimal_places=2, max_digits=16, validators=[swpm.models.validate_positive]),
        ),
    ]
