# Generated by Django 3.2.9 on 2022-03-06 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swpm', '0064_auto_20220220_1904'),
    ]

    operations = [
        migrations.AddField(
            model_name='fxvolatilityquote',
            name='atm_type',
            field=models.CharField(choices=[('Spot', 'Spot'), ('Fwd', 'Fwd'), ('DeltaNeutral', 'Deltaneutral')], max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='fxvolatilityquote',
            name='is_atm',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='fxvolatilityquote',
            name='delta',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='start_date',
            field=models.DateField(),
        ),
    ]
