# Generated by Django 3.2.9 on 2022-04-09 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swpm', '0065_auto_20220306_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fxvolatilityquote',
            name='atm_type',
            field=models.CharField(blank=True, choices=[('Spot', 'Spot'), ('Fwd', 'Fwd'), ('DeltaNeutral', 'Deltaneutral')], max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='fxvolatilityquote',
            name='delta',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fxvolatilityquote',
            name='delta_type',
            field=models.CharField(blank=True, choices=[('Spot', 'Spot'), ('PaSpot', 'Paspot'), ('Fwd', 'Fwd'), ('PaFwd', 'Pafwd')], max_length=8, null=True),
        ),
    ]
