# Generated by Django 3.2.9 on 2022-04-21 04:48

from django.db import migrations, models
import swpm.models


class Migration(migrations.Migration):

    dependencies = [
        ('swpm', '0066_auto_20220409_1216'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchedulePeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateField()),
                ('end', models.DateField()),
            ],
        ),
        migrations.AlterField(
            model_name='interestratequote',
            name='tenor',
            field=models.CharField(max_length=5, validators=[swpm.models.validate_period]),
        ),
    ]
