# Generated by Django 3.2.9 on 2022-04-27 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swpm', '0067_auto_20220421_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interestratequote',
            name='instrument',
            field=models.CharField(max_length=12),
        ),
    ]
