# Generated by Django 3.2.9 on 2022-07-20 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('swpm', '0070_auto_20220501_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ccy',
            name='rate_day_counter',
            field=models.CharField(blank=True, choices=[('Actual360', 'Actual360'), ('Actual365Fixed', 'Actual365Fixed'), ('ActualActual', 'Actualactual'), ('Thirty360', 'Thirty360')], default=None, max_length=24, null=True),
        ),
        migrations.AlterField(
            model_name='swapleg',
            name='fixed_rate',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=10),
        ),
        migrations.AlterField(
            model_name='swapleg',
            name='index',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='swpm.rateindex'),
        ),
    ]
